{"error": null, "issues": [{"address": 1447, "code": "{\n        retu", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_StakeFreezer_4: 0x0\ncalldata_StakeFreezer_32 + 4: 0x1\ncaller: 0x0\nstorage_0: 0x0\ncalldata_StakeFreezer_0: 0x608fac5f00000000000000000000000000000000000000000000000000000000\ncalldatasize_StakeFreezer: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/10/0x9568c8c783f7166a9b88d0047ad28efc43921242.sol", "function": "unfreezeUserStake(address,uint256)", "lineno": 461, "title": "Exception state", "type": "Informational"}, {"address": 1465, "debug": "calldata_StakeFreezer_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_StakeFreezer_4: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncaller: 0x0\nstorage_0: 0x0\ncalldata_StakeFreezer_0: 0x966f055400000000000000000000000000000000000000000000000000000000\ncalldatasize_StakeFreezer: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `freezeUserStake(address,uint256,bytes32)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/10/0x9568c8c783f7166a9b88d0047ad28efc43921242.sol", "function": "freezeUserStake(address,uint256,bytes32)", "lineno": 464, "title": "Integer Overflow ", "type": "Warning"}, {"address": 1478, "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_StakeFreezer_4: 0x1\ncalldata_StakeFreezer_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncaller: 0x0\nstorage_0: 0x0\ncalldata_StakeFreezer_0: 0x966f055400000000000000000000000000000000000000000000000000000000\ncalldatasize_StakeFreezer: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/10/0x9568c8c783f7166a9b88d0047ad28efc43921242.sol", "function": "freezeUserStake(address,uint256,bytes32)", "lineno": 464, "title": "Exception state", "type": "Informational"}], "success": true}