2019-07-31 11:33:20,603: [12] m.main:INFO: Registered plugins: DetectReentrancySimple, DetectInvalid, DetectSuicidal, DetectEnvInstruction, DetectExternalCallAndLeak, DetectUninitializedStorage, DetectIntegerOverflow, DetectDelegatecall, DetectUnusedRetVal, DetectReentrancyAdvanced, DetectUninitializedMemory
2019-07-31 11:33:20,604: [12] m.main:INFO: Beginning analysis
2019-07-31 11:33:20,628: [12] m.e.manticore:INFO: Starting symbolic create contract
2019-07-31 11:33:47,123: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-07-31 11:40:15,257: [636] m.c.worker:ERROR: Exception in state 1: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-07-31 11:41:08,323: [655] m.c.worker:ERROR: Exception in state 9: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-07-31 11:44:03,714: [633] m.c.worker:ERROR: Exception in state 0: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-07-31 11:44:05,497: [12] m.e.manticore:INFO: 25 alive states, 42 terminated states
2019-07-31 11:44:45,018: [12] m.e.manticore:INFO: Starting symbolic transaction: 1