{"error": null, "issues": [{"address": 630, "code": "ower(b, n);\n ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Fermat_32 + 68: 0x2\ncalldata_Fermat_0: 0xe8b6fa8000000000000000000000000000000000000000000000000000000000\ncalldatasize_Fermat: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xcbb447cc78f646af29df035a4ade69ab1eea22d4.sol", "function": "claim(int256,int256,int256,int256)", "lineno": 78, "title": "Exception state", "type": "Informational"}, {"address": 917, "code": "nction getBalance() view public r", "debug": "", "description": "In the function `withdraw()` the following predictable state variables are used to determine Ether recipient:\n- block.timestamp\n", "filename": "/unique_chucks/35/0xcbb447cc78f646af29df035a4ade69ab1eea22d4.sol", "function": "withdraw()", "lineno": 52, "title": "Dependence on predictable environment variable", "type": "Warning"}, {"address": 1175, "code": "i = 0; i < pow", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Fermat_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Fermat_32 + 68: 0x3\ncalldata_Fermat_0: 0xe8b6fa8000000000000000000000000000000000000000000000000000000000\ncalldatasize_Fermat: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xcbb447cc78f646af29df035a4ade69ab1eea22d4.sol", "function": "claim(int256,int256,int256,int256)", "lineno": 93, "title": "Exception state", "type": "Informational"}, {"address": 1222, "code": "o handle addition. ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Fermat_4: 0x705320639f5f763380aafb7df8be78bb3bfcabd0decb597b53599bffffce693b\ncalldata_Fermat_32 + 68: 0x3\ncalldata_Fermat_0: 0xe8b6fa8000000000000000000000000000000000000000000000000000000000\ncalldatasize_Fermat: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xcbb447cc78f646af29df035a4ade69ab1eea22d4.sol", "function": "claim(int256,int256,int256,int256)", "lineno": 101, "title": "Exception state", "type": "Informational"}], "success": true}