{
  "contract": "0xf558921f32f4c57f6149e32e317d5f118118fcdb",
  "tool": "mythril",
  "start": 1563566834.6314926,
  "end": 1563567457.1700857,
  "duration": 622.5385930538177,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 388,
        "code": "     ",
        "debug": "storage_0 + calldata_URIDistribution_4: 0x0\ncalldata_URIDistribution_0: 0x49c3ebd800000000000000000000000000000000000000000000000000000000\ncalldatasize_URIDistribution: 0x4\n",
        "description": "A possible integer underflow exists in the function `_function_0x49c3ebd8`.\nThe subtraction may result in a value < 0.",
        "filename": "/unique_chucks/15/0xf558921f32f4c57f6149e32e317d5f118118fcdb.sol",
        "function": "_function_0x49c3ebd8",
        "lineno": 1647,
        "title": "Integer Underflow",
        "type": "Warning"
      },
      {
        "address": 403,
        "code": "t64 createdTimestamp;\n\n      ",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_0 + calldata_URIDistribution_4: 0x0\ncalldata_URIDistribution_0: 0x49c3ebd800000000000000000000000000000000000000000000000000000000\ncalldatasize_URIDistribution: 0x4\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/15/0xf558921f32f4c57f6149e32e317d5f118118fcdb.sol",
        "function": "_function_0x49c3ebd8",
        "lineno": 1645,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 473,
        "code": "mp\n        uint64 createdTimestamp;\n\n       ",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_0 + calldata_URIDistribution_4: 0xfffa\n256_EXP_2*\nConcat(0,\n       15 +\n       Extract(3, 0, storage_0 + calldata_URIDistribution_4)): 0x1\nstorage_Concat(0,\n       Extract(15,\n               4,\n               65535 +\n               Extract(15,\n                       0,\n                       storage_0 + calldata_URIDistribution_4))) +\nkeccac_0_+_calldata_URIDistribution_4: 0x0\ncalldata_URIDistribution_0: 0x49c3ebd800000000000000000000000000000000000000000000000000000000\ncalldatasize_URIDistribution: 0x4\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/15/0xf558921f32f4c57f6149e32e317d5f118118fcdb.sol",
        "function": "_function_0x49c3ebd8",
        "lineno": 1644,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}