{
  "contract": "0xa121c7003e0be256cdb2f9f9c36442f1c30a066d",
  "tool": "mythril",
  "start": 1563685185.1621118,
  "end": 1563685206.166511,
  "duration": 21.004399299621582,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 4482,
        "code": "dd(uint256 a, ",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncalldata_WSCToken_4: 0x1\ncalldata_WSCToken_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_WSCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/36/0xa121c7003e0be256cdb2f9f9c36442f1c30a066d.sol",
        "function": "burn(uint256)",
        "lineno": 56,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 5713,
        "code": "@titl",
        "debug": "calldata_WSCToken_32 + 36: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WSCToken_32_+_4: 0xc050fffff320c00020003d81af848540000000000000040000110001bd062022\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WSCToken_4: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_3: 0x0\ncalldata_WSCToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_WSCToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_WSCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/36/0xa121c7003e0be256cdb2f9f9c36442f1c30a066d.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 65,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 5726,
        "code": " token\n * @dev",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_WSCToken_32 + 36: 0x53632f08ddbb360427befb69cb0d577a76825c1eb02b4cefbf971939ae256117\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WSCToken_32_+_4: 0xd32ba62e013a1e544c40f8298f8c838ef0ca495e903244487f8ba1f8c2a013e7\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x53632f08ddbb360427befb69cb0d577a76825c1eb02b4cefbf971939ae256117\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WSCToken_4: 0x53632f08ddbb360427befb69cb0d577a76825c1eb02b4cefbf971939ae256117\nstorage_3: 0x0\ncalldata_WSCToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_WSCToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_WSCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/36/0xa121c7003e0be256cdb2f9f9c36442f1c30a066d.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 65,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}