{"error": null, "issues": [{"address": 4512, "code": "_amount <= address(th", "debug": "The exception is triggered under the following conditions:\n\ncalldata_ZenArt_4: 0x0\nstorage_13: 0x0\ncalldata_ZenArt_0: 0x5e775a2700000000000000000000000000000000000000000000000000000000\ncalldatasize_ZenArt: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/16/0x40b41a2d4c5fb2da3e08b0a1bbd361b5dd1f7bdd.sol", "function": "_function_0x5e775a27", "lineno": 998, "title": "Exception state", "type": "Informational"}], "success": true}