2019-08-07 03:17:42,189: [12] m.main:INFO: Registered plugins: DetectReentrancySimple, DetectInvalid, DetectUnusedRetVal, DetectReentrancyAdvanced, DetectUninitializedStorage, DetectIntegerOverflow, DetectSuicidal, DetectExternalCallAndLeak, DetectEnvInstruction, DetectUninitializedMemory, DetectDelegatecall
2019-08-07 03:17:42,190: [12] m.main:INFO: Beginning analysis
2019-08-07 03:17:42,227: [12] m.e.manticore:INFO: Starting symbolic create contract
2019-08-07 03:17:53,608: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-07 03:25:16,060: [12] m.e.manticore:INFO: 11 alive states, 23 terminated states
2019-08-07 03:25:20,602: [12] m.e.manticore:INFO: Starting symbolic transaction: 1
2019-08-07 03:28:08,334: [5813] m.c.worker:ERROR: Exception in state 7: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-07 03:31:23,904: [5800] m.c.worker:ERROR: Exception in state 4: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-07 03:36:50,942: [5817] m.c.worker:ERROR: Exception in state 8: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-07 03:38:12,426: [5818] m.c.worker:ERROR: Exception in state 9: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-07 03:41:03,406: [5809] m.c.worker:ERROR: Exception in state 6: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 952, in _consume
    m = Z3Solver.instance().min(self.constraints, self._gas)
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 118, in min
    return self.optimize(constraints, X, "minimize", M)
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 508, in optimize
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError