{
  "contract": "0x902f3bd381d9b97db1b084f6bda64a0a54b6d2d5",
  "tool": "mythril",
  "start": 1563663932.2041223,
  "end": 1563663951.1436944,
  "duration": 18.93957209587097,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 3110,
        "code": "ozenFunds(_target, freeze);\n }\n",
        "debug": "",
        "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.",
        "filename": "/unique_chucks/33/0x902f3bd381d9b97db1b084f6bda64a0a54b6d2d5.sol",
        "function": "refundTokens(address,address,uint256)",
        "lineno": 371,
        "title": "Message call to external contract",
        "type": "Warning"
      },
      {
        "address": 5270,
        "code": " }\n\n  function",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0x1c000000000000000000000\ncalldata_VINCToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0x0\ncaller: 0x0\ncalldata_VINCToken_0: 0x7e1f2bb800000000000000000000000000000000000000000000000000000000\ncalldatasize_VINCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/33/0x902f3bd381d9b97db1b084f6bda64a0a54b6d2d5.sol",
        "function": "createTokens(uint256)",
        "lineno": 38,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 5288,
        "code": "\n  }\n",
        "debug": "calldata_VINCToken_4: 0x17b2f289e26040400967fa9\nstorage_4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfffffffffffffffffffffffffffffffffffffffffffbcf648e32d693e4e0ffad\nstorage_2: 0x0\ncaller: 0x0\ncalldata_VINCToken_0: 0x7e1f2bb800000000000000000000000000000000000000000000000000000000\ncalldatasize_VINCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `createTokens(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/33/0x902f3bd381d9b97db1b084f6bda64a0a54b6d2d5.sol",
        "function": "createTokens(uint256)",
        "lineno": 43,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 5301,
        "code": "**\n * ERC-20 s",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_VINCToken_4: 0x12799a2ebaded35316f2bd9\nstorage_4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffff24f930cb36c931257c0b99\nstorage_2: 0x0\ncaller: 0x0\ncalldata_VINCToken_0: 0x7e1f2bb800000000000000000000000000000000000000000000000000000000\ncalldatasize_VINCToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/33/0x902f3bd381d9b97db1b084f6bda64a0a54b6d2d5.sol",
        "function": "createTokens(uint256)",
        "lineno": 50,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}