{"error": null, "issues": [{"address": 558, "code": "tery\n * @dev Numbe", "debug": "storage_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_NumberLottery_4: 0x3\ncallvalue: 0x0\nstorage_2: 0x0\ncalldata_NumberLottery_0: 0x12333b3200000000000000000000000000000000000000000000000000000000\ncalldatasize_NumberLottery: 0x4\n", "description": "A possible integer overflow exists in the function `StartGame(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/29/0x2f069a1d7a052052458e8b5511e91221eb337c52.sol", "function": "StartGame(uint256)", "lineno": 2, "title": "Integer Overflow ", "type": "Warning"}, {"address": 1225, "code": "g;\n\n  modifier onlyOwner", "debug": "The exception is triggered under the following conditions:\n\ncalldata_NumberLottery_4: 0x0\nstorage_4: 0x0\ncalldata_NumberLottery_0: 0xf82c50f100000000000000000000000000000000000000000000000000000000\ncalldatasize_NumberLottery: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/29/0x2f069a1d7a052052458e8b5511e91221eb337c52.sol", "function": "_function_0xf82c50f1", "lineno": 24, "title": "Exception state", "type": "Informational"}], "success": true}