{"error": null, "issues": [{"address": 1485, "code": "      + u", "debug": "storage_2: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_ZmineStRandom_4: 0x8000000000000000000000000000000000000000000000000000000000000000\ncalldata_ZmineStRandom_32 + 4: 0x8000000000000000000000000000000000000000000000000000000000000001\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xff00\ncalldata_ZmineStRandom_0: 0x7299054c00000000000000000000000000000000000000000000000000000000\ncalldatasize_ZmineStRandom: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `random(uint256,uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/41/0xca46d9e80e7ad06e3f557764ec355e5aac6d6cb3.sol", "function": "random(uint256,uint256,uint256)", "lineno": 99, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3120, "code": "min, uint256 max, uint256 lotto) public onlyAuthori", "debug": "The exception is triggered under the following conditions:\n\ncalldata_ZmineStRandom_32 + 4: 0x0\nstorage_keccac_calldata_ZmineStRandom_4: 0x0\ncalldata_ZmineStRandom_0: 0xf65a74dc00000000000000000000000000000000000000000000000000000000\ncalldatasize_ZmineStRandom: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/41/0xca46d9e80e7ad06e3f557764ec355e5aac6d6cb3.sol", "function": "_function_0xf65a74dc", "lineno": 92, "title": "Exception state", "type": "Informational"}], "success": true}