{"error": null, "issues": [{"address": 1256, "code": "56 i;\n\t\tuint256 sum = 0;\n\n\t\tfor(i = 0; i < _amount.length; i++) {\n\t\t\tsum = sum.add(_amount[i]);\n\t\t\trequire(_tos[i] != address(0));\n\t\t}\n\n\t\trequire(balances[msg.sender] >= sum);\n\n\t\tfor(i = 0; i < _tos.length; i++)\n\t\t\ttransfer(_tos[i], _amount[i]);\n\n\t\treturn true;\n\t}\n}", "debug": "calldata_ZperToken_4: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_ZperToken_0: 0x88d695b200000000000000000000000000000000000000000000000000000000\ncalldatasize_ZperToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `batchTransfer(address[],uint256[])`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/2/0xb5b8f5616fe42d5ceca3e87f3fddbdd8f496d760.sol", "function": "batchTransfer(address[],uint256[])", "lineno": 152, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5915, "code": ";\n\t}\n\n/**\n * @", "debug": "The exception is triggered under the following conditions:\n\ncalldata_ZperToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_ZperToken_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_ZperToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/2/0xb5b8f5616fe42d5ceca3e87f3fddbdd8f496d760.sol", "function": "burn(uint256)", "lineno": 32, "title": "Exception state", "type": "Informational"}, {"address": 5932, "code": "}\n}\n\n", "debug": "calldata_ZperToken_32 + 36: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ZperToken_32_+_4: 0xc050fffff320c00020003d81af848540000000000000040000110001bd062022\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ZperToken_4: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\ncalldata_ZperToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_ZperToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_ZperToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/2/0xb5b8f5616fe42d5ceca3e87f3fddbdd8f496d760.sol", "function": "transferFrom(address,address,uint256)", "lineno": 42, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5945, "code": "act ZperToken ", "debug": "The exception is triggered under the following conditions:\n\nstorage_1: 0x1\ncalldata_ZperToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_ZperToken_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x0\ncaller: 0x0\ncalldata_ZperToken_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_ZperToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/2/0xb5b8f5616fe42d5ceca3e87f3fddbdd8f496d760.sol", "function": "mint(address,uint256)", "lineno": 45, "title": "Exception state", "type": "Informational"}], "success": true}