2019-08-05 05:37:14,974: [12] m.main:INFO: Registered plugins: DetectEnvInstruction, DetectReentrancySimple, DetectInvalid, DetectDelegatecall, DetectReentrancyAdvanced, DetectUninitializedStorage, DetectUnusedRetVal, DetectExternalCallAndLeak, DetectUninitializedMemory, DetectSuicidal, DetectIntegerOverflow
2019-08-05 05:37:14,974: [12] m.main:INFO: Beginning analysis
2019-08-05 05:37:14,986: [12] m.e.manticore:INFO: Starting symbolic create contract
2019-08-05 05:37:25,872: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-05 05:53:51,316: [471] m.c.worker:ERROR: Exception in state 6: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-05 05:54:08,157: [457] m.c.worker:ERROR: Exception in state 3: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-05 05:54:25,141: [481] m.c.worker:ERROR: Exception in state 9: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-05 05:55:21,741: [447] m.c.worker:ERROR: Exception in state 0: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-05 05:58:18,946: [449] m.c.worker:ERROR: Exception in state 1: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-05 06:07:12,026: [452] m.c.worker:ERROR: Exception in state 2: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError